# Site settings
author: Sara Garza
title: Lone Star Coder
header-img: img/home-bg.png
email: sjgarza22@gmail.com
copyright_name: Sara Garza
description: > # this means to ignore newlines until "baseurl:"
  My Trail to Becoming a Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: sjgarza22
github_username:  sjgarza22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
